### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by demist** [jullak/spaceStrategy#1]
+ не хватает схемы архитектуры
+ стоило бы все константы вынести в отдельный файл

все остальное - отлично, замечаний нет.

**Comment by jullak** [comment]
Схема добавлена.
В предположении, что константы + информацию по фракциям можно забирать из определенного типа источников (txt/бд/etc) добавлен класс FileManager, строковые и числовые константы вынесены в txt.

**Comment by demist** [comment]
Все отлично, засчитано
